### ISSUE TITLE
Alternative Kafka & ZooKeeper Docker images

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/kafka-bundle#3]
This issue is more for open discussion and not necessarily required for MVP but something for us to explore.

For our Kafka Docker image, we pull [confluentinc/cp-kafka](https://hub.docker.com/r/confluentinc/cp-kafka/), however for ZooKeeper, [we pull](https://github.com/astronomerio/kafka-k8s/blob/c6b30e683067d391b7c06dce4f42f1acafc827ee/zookeeper/templates/statefulset.yaml#L39) a sample image from Google, [gcr.io/google_samples/k8szk:v2](https://console.cloud.google.com/gcr/images/google-samples/GLOBAL/k8szk@sha256:32212dd754b6280ac6c96b615605300f1f060baad1fdf68abd370d2ffb07ae47/details/info).  These are the defaults from kubernetes/charts.

- I noticed the ZK image tag [v2](https://console.cloud.google.com/gcr/images/google-samples/GLOBAL/k8szk@sha256:32212dd754b6280ac6c96b615605300f1f060baad1fdf68abd370d2ffb07ae47/details/info) is from Dec 2016 and there's a [v3](https://console.cloud.google.com/gcr/images/google-samples/GLOBAL/k8szk@sha256:eee48b4ab091324993baec42ee542f26836acfd24821eb3891e5a7c281b80dad/details/info) tag from Oct 2017.  Do we want to try using the newer one?
- Should we consider replacing the Google image with Confluent's ZooKeeper, [confluentinc/cp-zookeeper](https://hub.docker.com/r/confluentinc/cp-zookeeper/), instead?
- Btw, there's also another image from Google called [kubernetes-zookeeper](https://console.cloud.google.com/gcr/images/google-samples/GLOBAL/kubernetes-zookeeper?gcrImageListsize=50) which I'm not sure if that's different from k8szk.
- Google also has a [k8skafka](https://console.cloud.google.com/gcr/images/google-samples/GLOBAL/k8skafka?gcrImageListsize=50) image which we haven't explored yet.

What do you guys think?

**Comment by tedmiston** [comment]
I got a reply back on my SO question from a Google engineer who said their sample ZooKeeper image is not actively maintained and shouldn't be used for production use (he just opened https://github.com/kubernetes/charts/issues/4540).

Given that, I'm going to give Confluent's ZooKeeper image a go instead.

**Comment by cristian04** [comment]
One of the differences between these images is that the google ones implements a couple of scripts that are not available on the confluentinc ones.

@tedmiston Could you please share your experiences with the confluentinc? PR #4729 allows you to specify a different image, but it needs some extra work to parmeterize the entry points

**Comment by tedmiston** [comment]
Yep, I'll post back here after playing with them a bit more.  If we can get the Confluent ZooKeeper image working just as well, I'll send a PR to kubernetes/charts.

That PR looks interesting.  We could build this on top of that

**Comment by andscoop** [comment]
@tedmiston I think we can close this one out. Reopen at a later date if it needs reworked.

**Comment by lalarsson** [comment]
@tedmiston Was there any particular reason for giving up a more production ready image for ZK?

**Comment by tedmiston** [comment]
IIRC the production ready one wasn't used in the Helm chart and the Confluent vs Google images had different entry point setups, extras, etc.  The Google engineer opened a ticket to migrate the Helm chart image off their test image, so that's probably not an issue today.  I would use the Confluent images for both for prod work today.

**Comment by lalarsson** [comment]
I see, I made a configuration for using a Confluent image earlier today - should I perhaps open a PR with the changes I did?

**Comment by tedmiston** [comment]
Yeah.  We're not actively using this repo currently but if you mean that the Kafka / ZK official Helm charts are using images besides the Confluent ones, I think that'd be a welcome PR.
