### ISSUE TITLE
Debug & resolve Kafka Manager spin crash

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/kafka-bundle#8]
Something is causing the Kafka Manager pod to crash in the umbrella chart setup.

```
t-mbp:~ taylor$ kubectl port-forward $POD_NAME 8080:9000
Forwarding from 127.0.0.1:8080 -> 9000
Handling connection for 8080
E0328 12:10:51.012479   12248 portforward.go:331] an error occurred forwarding 8080 -> 9000: error forwarding port 9000 to pod 50cbf9f57fb7ab85ca4812c71dc886f7f1a2fc1a1971caf911d2f19191491084, uid : exit status 1: 2018/03/28 16:10:51 socat[685] E connect(6, AF=2 127.0.0.1:9000, 16): Connection refused
```

For whatever reason we weren't experiencing this when the chart was run in isolation.

**Comment by andscoop** [comment]
similar issue for reference
https://github.com/yahoo/kafka-manager/issues/395

**Comment by andscoop** [comment]
I am able to get this running outside of K8s but inside docker.

Findings:
```
[info] o.a.z.ClientCnxn - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[warn] o.a.z.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
```
This error is not related to the performance of the dashboard itself.

---

The sheepkiller docker image we are using is behind by a few mini-versions.
https://github.com/yahoo/kafka-manager/releases/tag/1.3.1.8

Testing locally I am not able to get the 1.3.1.8 tag to run without errors on the dashboard. This is not a problem when running the latest kafka-manager release.

In general we should at the very least we should re-host any of these docker images once we are out of dev.

**Comment by tedmiston** [comment]
Are you sure that's the tag you meant to link to?  It says 1.3.1.8 from Sep 7, 2016.  I'm seeing a latest tag of 1.3.3.17 from Mar 17, 2018.

In any case, yeah, I think we'll have to build it ourselves to have the latest — but I see that as a good thing since it lets us control release of all of the Docker images through one org on DockerHub.

**Comment by andscoop** [comment]
That is correct - I was able to get latest working but unable to get 1.3.1.8 working.

**Comment by tedmiston** [comment]
Worked on this today.

I've forked the sheepkiller kafka-manager-docker and updated the Dockerfile to pull the latest Kafka Manager (1.3.3.17).

The build is failing obscurely for me downloading dependencies but I think it's related to the enterprise network here.

Here's what I'm running:

	git clone https://github.com/astronomerio/kafka-manager-docker.git
	cd kafka-manager-docker
	docker build .

**Comment by andscoop** [comment]
Closing out with other 84.51 services tickets. Can re-open at later date if needed.
